### PR TITLE
fix: pipelines issues

### PR DESCRIPTION
**Pull request by astlock**
## Pull Request 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other: (describe here) 
  
## Proposed Change

Issue Number: N/A

## Breaking Change?

- [ ] Yes
- [ ] No

## Checklist

Please validate that your PR fulfills the following requirements:
- [ ] I have read the **CONTRIBUTING.md** documentation (if available)
- [ ] I have branched from the default repo branch (can be master, main, or release/vX.X)
- [ ] I have checked that a similar PR does not exist or has been rejected in the past
- [ ] PR changes are specific to a feature or bug
- [ ] No style/format/cosmetic changes included
- [ ] I have used existing style and naming patterns in my changes
- [ ] Tests for the changes have been added/updated (if relevant)
- [ ] Built/compiled and tested locally
- [ ] Docs have been added/updated (if relevant)
- [ ] I have squashed my changes into a single commit

### CODE REVIEW

**Review by NorseGaud — APPROVED** [review]

**Comment by astlock** [comment]
WIP

**Comment by NorseGaud** [comment]
Good catch!

**Review by NorseGaud — COMMENTED** [review]
Fortunately the `anka registry` command has an option to set the registry URL to pull/push from:

```
❯ anka registry --help
Usage: anka registry [OPTIONS] COMMAND [ARGS]...

  Configure and control the Anka Cloud Registry

Options:
. . .
  -a, --registry-path TEXT    Set the registry URL (instead of 'default')
```

Could you use that instead? If the parameter is empty, it could just omit `-a` and use the local one the user configures manually.

**Comment by astlock** [comment]
> Fortunately the `anka registry` command has an option to set the registry URL to pull from:
> 
> ```
> ❯ anka registry --help
> Usage: anka registry [OPTIONS] COMMAND [ARGS]...
> 
>   Configure and control the Anka Cloud Registry
> 
> Options:
> . . .
>   -a, --registry-path TEXT    Set the registry URL (instead of 'default')
> ```
> 
> Could you use that instead? If the parameter is empty, it could just omit `-a` and use the local one the user configures manually.

Cool! Didn't know that flag. Let me fix

**Comment by NorseGaud** [comment]
Hi @astlock, do you mind if we merge the current state?

**Comment by astlock** [comment]
> Hi @astlock, do you mind if we merge the current state?

Yeah, sure! Didn't find anything else critical.

**Pull request merged**
